export const siteConfig = {
	name: "{{name}}",
	url: "https://{{name}}.colidevs.com",
	ogImage: "https://{{name}}.colidevs.com/og.jpg",
	description: "{{name}} generated by colidevs cli",
	links: {
		instagram: "https://instagram.com/colidevs",
	},
};

export type SiteConfig = typeof siteConfig;
