import { Icons } from "@/components/icons";
import { cn } from "@/lib/utils";
import { unstable_ViewTransition as ViewTransition } from "react";

export default function Home() {
	return (
		<ViewTransition name="page">
			<main className={cn("flex flex-1 flex-col items-center")}>
				<div className="mt-64 z-10">
					<p className="text-muted-foreground">project generated by</p>
					<Icons.logoImg />
				</div>
			</main>
		</ViewTransition>
	);
}
