const {
  GCP_CREDENTIALS_PROJECT_ID,
  GCP_CREDENTIALS_PRIVATE_KEY_ID,
  GCP_CREDENTIALS_PRIVATE_KEY,
  GCP_CREDENTIALS_CLIENT_EMAIL,
  GCP_CREDENTIALS_CLIENT_ID,
} = process.env;

export const config = {
  gcp: {
    credentials: {
      PROJECT_ID: GCP_CREDENTIALS_PROJECT_ID,
      KEY_ID: GCP_CREDENTIALS_PRIVATE_KEY_ID,
      KEY: GCP_CREDENTIALS_PRIVATE_KEY,
      CLIENT_EMAIL: GCP_CREDENTIALS_CLIENT_EMAIL,
      CLIENT_ID: GCP_CREDENTIALS_CLIENT_ID,
    },
  },
};
